/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class MyHID */

#ifndef _Included_MyHID
#define _Included_MyHID
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     MyHID
 * Method:    ReadFeatureReportSize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_MyHID_ReadFeatureReportSize
  (JNIEnv *, jobject);

/*
 * Class:     MyHID
 * Method:    ReadInputReportSize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_MyHID_ReadInputReportSize
  (JNIEnv *, jobject);

/*
 * Class:     MyHID
 * Method:    ReadOutputReportSize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_MyHID_ReadOutputReportSize
  (JNIEnv *, jobject);

/*
 * Class:     MyHID
 * Method:    ReadFeatureReport
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_MyHID_ReadFeatureReport
  (JNIEnv *, jobject);

/*
 * Class:     MyHID
 * Method:    IntReadInputReport
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_MyHID_IntReadInputReport
  (JNIEnv *, jobject);

/*
 * Class:     MyHID
 * Method:    CtrlReadInputReport
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_MyHID_CtrlReadInputReport
  (JNIEnv *, jobject);

/*
 * Class:     MyHID
 * Method:    SendFeatureReport
 * Signature: ([B)Z
 */
JNIEXPORT jboolean JNICALL Java_MyHID_SendFeatureReport
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     MyHID
 * Method:    IntSendOutputReport
 * Signature: ([B)Z
 */
JNIEXPORT jboolean JNICALL Java_MyHID_IntSendOutputReport
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     MyHID
 * Method:    CtrlSendOutputReport
 * Signature: ([B)Z
 */
JNIEXPORT jboolean JNICALL Java_MyHID_CtrlSendOutputReport
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     MyHID
 * Method:    FindTheHID
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_MyHID_FindTheHID
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     MyHID
 * Method:    CloseHandles
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_MyHID_CloseHandles
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
